### ISSUE TITLE
Feature Request: doc of Typora

### ISSUE THREAD

**Issue by BobAnkh** [duskmoon314/THU_EXP#4]
# 打算完善/docs/Typora.md中使用部分

1. 基本操作

    计划包括文件、段落、格式选单基本介绍，以及源代码模式介绍。是否需要其他内容介绍。

2. 更改主题

    计划包括主题下载与更改使用。

以上内容计划4日内完成

**Comment by BobAnkh** [comment]
@duskmoon314 
可以插图片吗？或许更直观。

图片目录是怎么处理？

**Comment by duskmoon314** [comment]
@BobAnkh 
存放在`/assets/images`下吧

**Comment by BobAnkh** [comment]
@duskmoon314 
终于抽出时间把这个长久以前的工作完成了——关于Typora的基本介绍
#6 请检查并审阅

**Comment by duskmoon314** [comment]
#6 Merged
